language: csharp
mono: 6.8.0
dotnet: 2.1.804
os:
  - linux
  - osx
sudo: true
dist: xenial
osx_image: xcode9.4.1

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dotnet-sdk-3.1 ; fi
 
addons:
  apt:
    sources:
    packages:
script: 
  - echo "========== restore all .Net Core samples ============"
  - dotnet restore "UA Sample Applications.sln"
  - dotnet restore "UA Global Discovery Server.sln"
  - dotnet restore "UA Quickstart Applications.sln"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dotnet restore "UA Aggregation.sln" ; fi
  - echo "========== build all .Net Core samples ============"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dotnet build -c Debug Workshop/Aggregation/ConsoleAggregationServer/ConsoleAggregationServer.csproj ; fi
  - dotnet build -c Debug Samples/NetCoreConsoleClient/NetCoreConsoleClient.csproj
  - dotnet build -c Debug Samples/NetCoreComplexClient/NetCoreComplexClient.csproj
  - dotnet build -c Debug Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj
  - dotnet build -c Release Workshop/Aggregation/ConsoleAggregationServer/ConsoleAggregationServer.csproj
  - dotnet build -c Release Samples/NetCoreConsoleClient/NetCoreConsoleClient.csproj
  - dotnet build -c Release Samples/NetCoreComplexClient/NetCoreComplexClient.csproj
  - dotnet build -c Release Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj
  - dotnet build -c Debug Samples/GDS/ConsoleServer
  - dotnet build -c Release Samples/GDS/ConsoleServer
  - echo "========== run .Net Core samples ============"
  - cd Samples/NetCoreConsoleServer/bin/Debug/netcoreapp2.1
  - dotnet NetCoreConsoleServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testclientserver.sh
  - echo "========== build all Mono samples ============"
  - msbuild /t:restore Samples/NetCoreConsoleServer/MonoConsoleServer.csproj
  - msbuild /p:configuration=Debug /t:compile,publish Samples/NetCoreConsoleServer/MonoConsoleServer.csproj
  - msbuild /p:configuration=Release /t:compile,publish Samples/NetCoreConsoleServer/MonoConsoleServer.csproj
  - msbuild /t:restore Samples/NetCoreConsoleClient/MonoConsoleClient.csproj
  - msbuild /p:configuration=Debug /t:compile,publish Samples/NetCoreConsoleClient/MonoConsoleClient.csproj
  - msbuild /p:configuration=Release /t:compile,publish Samples/NetCoreConsoleClient/MonoConsoleClient.csproj
  - cd Samples/NetCoreConsoleServer/bin/Debug/net462
  - mono MonoConsoleServer.exe -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testmonoclientserver.sh

after_script:
  - echo "========== build done ============"

after_failure:
  - cd $HOME
  - cd .local/share/OPC
  - ls -R
  - cd Logs
  - cat GlobalDiscoveryTestClient.log.txt
  - cat ServerConfigurationPushTestClient.log.txt
  - cat GlobalDiscoveryTestServer.log.txt
  - cd $TRAVIS_BUILD_DIR


